config/routes.rb
Rails.application.routes.draw do
  root to: "admins#index"

  get 'see', to: "registration#index"

  get "sign_up", to:"registration#new"

  post "sign_up", to: "registration#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in", to:"sessions#new"

  post "sign_in", to: "sessions#create"

  get "see_books", to: "books_page#index"

  get "add_book", to: "books_page#new"
  post "add_book", to: "books_page#create"
  delete "delete_book", to: "books_page#destroy"

  get "issue_book", to: "book_issue#new"
  get "show_book", to: "book_issue#show"
  post "issue_book", to: "book_issue#create"

  get "return_book", to: "book_issue#return"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :author, presence: true
  validates :published_in, presence: true
  validates :volume, presence: true
  has_many :issued_books
  has_many :students, through: :issued_books

  def self.check_issue_status(title)
    @book = Book.find_by(title: title)
    @book.students.present?
  end


  def self.update_book(params,student)
    @book = Book.find_by(title: params[:book_issued])
    puts(@book)
    puts "************"
    @book.students << student
    puts(@book.issued_books.first)
    issued_book_record= @book.issued_books.first 
    issued_book_record.issued = true
    issued_book_record.issued_date = params[:issued_date].to_s
    issued_book_record.return_Date = params[:issued_date].to_s
    issued_book_record.save

  end

  def self.book_returned(params)
    @book = Book.find(params[:id])
    @book.issued_books.destroy_all
    @book.students.destroy_all

  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/issued_book.rb
class IssuedBook < ApplicationRecord
  belongs_to :book
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  validates :email, format: {with: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/}, presence: true
  validates :name, presence: true
  has_many :issued_books
  has_many :books, through: :issued_books


  def self.valiadte_student(params)
    !(params[:name].empty? && params[:email].empty? && params[:issued_date].empty? && params[:return_date].empty?)
  end

  def self.update_student(params)
    if Student.find_by(name: params[:name]).present?
      @student = Student.find_by(name: params[:name])
      Book.update_book(params,@student)
      # redirect_to see_books_path, notice: "Book Issued"
    else
      @student = Student.create(name: params[:name],email: params[:email])
      Book.update_book(params,@student)
      # redirect_to see_books_path, notice: "Book Issued"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, format: {with: /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/}, uniqueness: true
  validates :password, presence: true
  validates :confirm_password, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @books = Book.all
  end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You Must login first to do that" if Current.user.nil?
  end
end

app/controllers/book_issue_controller.rb
class BookIssueController < ApplicationController
  before_action :require_user_logged_in!
  def new
    @book = Book.find(params[:id])
    @student = Student.new
  end

  def show
    @book = Book.find(params[:id])
  end
  
  def create
    @student = Student.new
    @book = Book.find_by(title: params[:book_issued])
    if Book.check_issue_status(params[:book_issued])
      redirect_to see_books_path, alert: "Book Already issued"
    elsif Student.valiadte_student(params)
      # puts Student.find_by(name: params[:name]).id
      Student.update_student(params)
      redirect_to see_books_path, notice: "Book Issued"
    else
      # render :new, status: :unprocessable_entity, id: params[:id]
      redirect_to issue_book_url(id: @book.id), alert: "Students details are not available"
    end
  end

  def return
    Book.book_returned(params)
    redirect_to see_books_path, notice: "Book Returned"
  end

end

app/controllers/bookissue_controller.rb
class BookissueController < ApplicationController
  before_action :require_user_logged_in!
  def new
    @book = Book.find(params[:id])
    @student = Student.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @student = Student.new(student_params)

    if Book.checkIssueStatus(@student)
      redirect_to seeBooks_path, alert: "Book Already issued"
    elsif @student.save
      Book.updateBook(@student)
      redirect_to seeBooks_path, notice: "Book Issued"
    else
      # flash[:alert] = "Something went worng" 
      # puts @student.errors.full_messages
      # @errors = @student.errors.full_messages

      # render :new, status: :unprocessable_entity
      redirect_to seeBooks_path, alert: "Students details are not available"
    end
  end

  def return
    Book.bookReturned(params)
    redirect_to seeBooks_path, notice: "Book Returned"
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :bookIssued, :issuedDate, :returnDate)
  end
end

app/controllers/books_page_controller.rb
class BooksPageController < ApplicationController
  before_action :require_user_logged_in!
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to see_books_path, notice: "Successfully Added book to database"
    else
      # flash[:alert] = "Fill out Book details"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other, alert: "Book removed"
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :published_in, :volume)
  end
end

app/controllers/bookspage_controller.rb
class BookspageController < ApplicationController
  before_action :require_user_logged_in!
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to seeBooks_path, notice: "Successfully Added book to database"
    else
      flash[:alert] = "Fill out Book details"
      # @errors = @book.errors.full_messages 
      # puts @book.errors.full_messages 
      render :new, status: :unprocessable_entity
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :published_in, :volume)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def index
    @user = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to see_books_path, notice: "Successfully created account"
    else
      # flash[:alert] = "Something went worng"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :confirm_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    
    if user.present? && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to see_books_path, notice: "Logged In Successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admins/index.html.erb
<h1>Sign In / Sign Up as Admin</h1>
<p>Add new arrived books to Database</p>

<div class="d-flex gap-4">
  <% if !Current.user%>
    <%= button_to "Sign In", sign_in_path, method: :get%>
    <%= button_to "Sign Up", sign_up_path, method: :get%>
  <%end%>
</div>

<div class="mt-4">
  <h3>Available books</h3>
</div>
<div class="p-3 mb-4 mt-3">
  <% @books.each do |book|%>
    <li class ="d-flex gap-3 p-3 shadow ">
        <div class="fs-5 text-primary me-2">
          <%= book.title%>
        </div>
        <div >By
          <span class="fs-5 text-danger me-2">
          <%= book.author%></span>
        </div>
        <div>Part
          <span class="fs-5 text-info me-2 ms-1">
          <%= book.volume%></span>
        </div>
        <div >published in
          <span class="fs-5 text-danger me-5 ms-1">
          <%= book.published_in%></span>
        </div>
        <%if Current.user%>
          <div class="ms-auto">
            <% if book[:issued] %>
              <div class="btn btn-danger">issued</div>
            <%else%>
              <div class="btn btn-warning"><%= link_to "Issue Book", issue_book_path(id: book[:id])%></div>
            <%end%>

            <div class="btn btn-outline-info"><%= link_to "Show Details", show_book_path(id: book[:id])%></div>

        </div>
        <%end%>
    </li>
  <% end %>
</div>

<%if !Current.user%>
  <%= link_to "Add new Book", sign_in_path, class:"nav-link btn"%>
<%end%>

app/views/admins/show_signIn.html.erb
<h1 class="text-muted d-flex justify-content-center">Sign In</h1>

<%= form_with url: sign_in_path do |form| %>
  
  <div class="mb-3">
    <%= form.label :email, class:"mb-2"%>
    <%= form.text_field :email, class:"form-control", placeholder: "abc@gmail.com"%>
  </div>
  <div class="mb-3">
    <%= form.label :password, class:"mb-2"%>
    <%= form.password_field :password, class:"form-control", placeholder:"password"%>
  </div>
  <div class="mb-3">
    <%= form.submit "Sign Up", class:"btn btn-primary"%>
  </div>

<% end %>

app/views/admins/show_signUp.html.erb
<h1 class="text-muted d-flex justify-content-center">Sign Up</h1>

<%= form_with url: sign_up_path do |form| %>
  
  <div class="mb-3">
    <%= form.label :email, class:"mb-2"%>
    <%= form.text_field :email, class:"form-control", placeholder: "abc@gmail.com"%>
  </div>
  <div class="mb-3">
    <%= form.label :password, class:"mb-2"%>
    <%= form.password_field :password, class:"form-control", placeholder:"password"%>
  </div>
  <div class="mb-3">
    <%= form.label :Confirm_password, class:"mb-2"%>
    <%= form.password_field :Confirm_password, class:"form-control", placeholder:"password"%>
  </div>
  <div class="mb-3">
    <%= form.submit "Sign Up", class:"btn btn-primary"%>
  </div>

<% end %>

app/views/book_issue/new.html.erb
<h2 class="d-flex mb-3 justify-content-center text-muted">Issue book </h2>

<div class="d-flex align-items-center flex-column shadow p-2 bg-light text-scondary gap-3 mb-3"> 
  <div class="fs-4 text-warning">
    <%= @book[:title]%>
  </div>
  <div>
    Author: <%= @book[:author]%>
  </div>
  <div>
    Published in: <%= @book[:published_in]%>
  </div>
  <div>
    Volume: <%= @book[:volume]%>
  </div>
  <div>
    Issue Status:
    <span class="text-danger">
    <% if @book.issued_books.present?%>
      issued
    <%else%>
      Not issued
    <%end%><span>
  </div>
</div>
<h1 class="text-muted">Student Details</h1>

<%= form_with url: issue_book_path(id: @book[:id]), local: :true do |form| %>

  <div class="mb-3">
    <%= form.label :name, class:"mb-2"%>
    <%= form.text_field :name, class:"form-control", placeholder: "student name"%>
  </div>
  <div class="mb-3">
    <%= form.label :email, class:"mb-2"%>
    <%= form.email_field :email, class:"form-control", placeholder: "abc@gmail.com"%>
  </div>
  <div class="mb-3">
    <%= form.label :book_issued, class:"mb-2"%>
    <%= form.text_field :book_issued, class:"form-control", value: @book[:title]%>
  </div>
  <div class="mb-3">
    <%= form.label :issued_date, class:"mb-2"%>
    <%= form.date_field :issued_date, class:"form-control"%>
  </div>
  <div class="mb-3">
    <%= form.label :return_date, class:"mb-2"%>
    <%= form.date_field :return_date, class:"form-control"%>
  </div>
  <div class="mb-3">
    <%= form.submit "Issue Book", class:"btn btn-primary"%>
  </div>

<% end %>

app/views/book_issue/show.html.erb
<h2 class="d-flex mb-3 justify-content-center text-muted">Book Details</h2>

<div class="d-flex align-items-center flex-column shadow p-2 bg-light text-scondary gap-3 mb-3"> 
  <div class="fs-4 text-warning">
    <%= @book[:title]%>
  </div>
  <div>
    Author: <%= @book[:author]%>
  </div>
  <div>
    Published in: <%= @book[:published_in]%>
  </div>
  <div>
    Volume: <%= @book[:volume]%>
  </div>
  <div>
    Issue Status:
    <span class="text-danger">
    <% if @book.issued_books.present?%>
      issued
    <%else%>
      Not issued
    <%end%><span>
  </div>

  <div>
    Issued To:
    <span class="text-primary fs-5">
    <% if !@book.issued_books.present?%>
      Not Issued Yet
    <%else%>
      <%= @book.issued_books.first.student.name%> 
    <%end%><span>
  </div>

  <div>
    <%if @book.issued_books.present?%>
      <div>
        Issue Date : <%= @book.issued_books.first.issued_date%>
      </div>
      <div>
        Return Date : <%= @book.issued_books.first.return_Date%>
      </div>
    <%end%>
  </div>
</div>

<% if @book.issued_books.present?%>
  <div class="btn btn-outline-info p-0"><%= link_to "Recieve Book", return_book_path(id: @book[:id]), class:"nav-link" %></div>
<%end%>

app/views/bookissue/new.html.erb
<h2 class="d-flex mb-3 justify-content-center text-muted">Issue book </h2>

<div class="d-flex align-items-center flex-column shadow p-2 bg-light text-scondary gap-3 mb-3"> 
  <div class="fs-4 text-warning">
    <%= @book[:title]%>
  </div>
  <div>
    Author: <%= @book[:author]%>
  </div>
  <div>
    Published in: <%= @book[:published_in]%>
  </div>
  <div>
    Volume: <%= @book[:volume]%>
  </div>
  <div>
    Issue Status:
    <span class="text-danger">
    <% if @book[:issued]%>
      issued
    <%else%>
      Not issued
    <%end%><span>
  </div>
</div>
<h1 class="text-muted">Student Details</h1>

<%= form_with model: @student, url: issueBook_path do |form| %>
  <%= @errors.inspect%>
  <% if @student.errors.any? %>
    <div class="alert alert-danger">
      <% @student.errors.full_messages.each do |message| %>
        <div><%= message%></div>
      <%end%>
    </div>
  <%end%>
  <div class="mb-3">
    <%= form.label :name, class:"mb-2"%>
    <%= form.text_field :name, class:"form-control", placeholder: "student name"%>
  </div>
  <div class="mb-3">
    <%= form.label :email, class:"mb-2"%>
    <%= form.email_field :email, class:"form-control", placeholder: "abc@gmail.com"%>
  </div>
  <div class="mb-3">
    <%= form.label :bookIssued, class:"mb-2"%>
    <%= form.text_field :bookIssued, class:"form-control", value: @book[:title]%>
  </div>
  <div class="mb-3">
    <%= form.label :issuedDate, class:"mb-2"%>
    <%= form.date_field :issuedDate, class:"form-control"%>
  </div>
  <div class="mb-3">
    <%= form.label :returnDate, class:"mb-2"%>
    <%= form.date_field :returnDate, class:"form-control"%>
  </div>
  <div class="mb-3">
    <%= form.submit "Issue Book", class:"btn btn-primary"%>
  </div>

<% end %>

app/views/bookissue/show.html.erb
<h2 class="d-flex mb-3 justify-content-center text-muted">Book Details</h2>

<div class="d-flex align-items-center flex-column shadow p-2 bg-light text-scondary gap-3 mb-3"> 
  <div class="fs-4 text-warning">
    <%= @book[:title]%>
  </div>
  <div>
    Author: <%= @book[:author]%>
  </div>
  <div>
    Published in: <%= @book[:published_in]%>
  </div>
  <div>
    Volume: <%= @book[:volume]%>
  </div>
  <div>
    Issue Status:
    <span class="text-danger">
    <% if @book[:issued]%>
      issued
    <%else%>
      Not issued
    <%end%><span>
  </div>

  <div>
    Issued To:
    <span class="text-primary fs-5">
    <% if @book[:issuedTo] == 'student' || @book[:issuedTo] == 'return' %>
      Not Issued Yet
    <%else%>
      <%= @book[:issuedTo]%> 
    <%end%><span>
  </div>

  <div>
    <%if @book[:issued]%>
      <div>
        Issue Date : <%= @book[:issuedDate]%>
      </div>
      <div>
        Return Date : <%= @book[:returnDate]%>
      </div>
    <%end%>
  </div>
</div>

<% if @book[:issued]%>
  <div class="btn btn-outline-info"><%= link_to "Recieve Book", returnBook_path(id: @book[:id]), class:"nav-link" %></div>
<%end%>

app/views/books_page/index.html.erb
<h1>This is page after sigup/sign_in</h1>

<div class="mt-4">
  <h3>Available books</h3>
</div>

<div class="p-3 mb-4 mt-3">
  <% @books.each do |book|%>
    <li class ="d-flex gap-3 p-3 shadow ">
        <div class="fs-5 text-primary me-2">
          <%= book.title%>
        </div>
        <div >By
          <span class="fs-5 text-danger me-2">
          <%= book.author%></span>
        </div>
        <div>Part
          <span class="fs-5 text-info me-2 ms-1">
          <%= book.volume%></span>
        </div>
        <div >published in
          <span class="fs-5 text-danger me-5 ms-1 ">
          <%= book.published_in%></span>
        </div>
        <div class="ms-auto">
          <% if book.issued_books.present? %>
            <div class="btn btn-danger">issued</div>
          <%else%>
            <div class="btn btn-warning p-0"><%= link_to "Issue Book", issue_book_path(id: book[:id]), class:"nav-link"%></div>
          <%end%>
          <div class="btn btn-outline-info p-0"><%= link_to "Show Details", show_book_path(id: book[:id]), class:"nav-link"%></div>
        </div>
        <div>
          <% if !book.issued_books.present?%>
            <%= button_to "Remove Book", delete_book_path(id: book[:id]), method: :delete, class:"btn btn-outline-secondary ms-2"%>
          <%end%>
        </div>
    </li>
  <% end %>
</div>

<%= link_to "Add new Book", add_book_path, class:"nav-link"%>

app/views/books_page/new.html.erb
<h1 class="text-muted d-flex justify-content-center">Add Book Details</h1>
<%= form_with model: @book, url: add_book_path, local: :true do |form| %>
  <div class="mb-3">
    <%= form.label :title, class:"mb-2"%>
    <%= form.text_field :title, class:"form-control", placeholder: "abc@gmail.com"%>
    <% if @book.errors.full_messages_for(:title).any?%>
        <div class="alert alert-danger mt-2">
            <% @book.errors.full_messages_for(:title).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <%end%>

  </div>
  <div class="mb-3">
    <%= form.label :author, class:"mb-2"%>
    <%= form.text_field :author, class:"form-control", placeholder:"Author name"%>
    <% if @book.errors.full_messages_for(:author).any?%>
        <div class="alert alert-danger mt-2">
            <% @book.errors.full_messages_for(:author).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <%end%>
  </div>

  <div class="mb-3">
    <%= form.label :volume, class:"mb-2"%>
    <%= form.text_field :volume, class:"form-control", placeholder:"Volume"%>
    <% if @book.errors.full_messages_for(:volume).any?%>
        <div class="alert alert-danger mt-2">
            <% @book.errors.full_messages_for(:volume).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <%end%>
  </div>

  <div class="mb-3">
    <%= form.label :published_in, class:"mb-2"%>
    <%= form.text_field :published_in, class:"form-control", placeholder:"published date"%>
    <% if @book.errors.full_messages_for(:published_in).any?%>
        <div class="alert alert-danger mt-2">
            <% @book.errors.full_messages_for(:published_in).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <%end%>
  </div>

  <div class="mb-3">
    <%= form.submit "Add Book", class:"btn btn-primary"%>
  </div>

<% end %>

app/views/bookspage/index.html.erb
<h1>This is page after sigup/signIn</h1>

<div class="mt-4">
  <h3>Available books</h3>
</div>

<div class="p-3 mb-4 mt-3">
  <% @books.each do |book|%>
    <li class ="d-flex gap-3 p-3 shadow ">
        <div class="fs-5 text-primary me-2">
          <%= book.title%>
        </div>
        <div >By
          <span class="fs-5 text-danger me-2">
          <%= book.author%></span>
        </div>
        <div>Part
          <span class="fs-5 text-info me-2 ms-1">
          <%= book.volume%></span>
        </div>
        <div >published in
          <span class="fs-5 text-danger me-5 ms-1 ">
          <%= book.published_in%></span>
        </div>
        <div class="ms-auto">
          <% if book[:issued] %>
            <div class="btn btn-danger">issued</div>
          <%else%>
            <div class="btn btn-warning"><%= link_to "Issue Book", issueBook_path(id: book[:id]), class:"nav-link"%></div>
          <%end%>
          <div class="btn btn-outline-info"><%= link_to "Show Details", showBook_path(id: book[:id]), class:"nav-link"%></div>
        </div>
    </li>
  <% end %>
</div>

<%= link_to "Add new Book", addBook_path, class:"nav-link"%>

app/views/bookspage/new.html.erb
<h1 class="text-muted d-flex justify-content-center">Add Book Details</h1>
<%= form_with model: @book, url: addBook_path do |form| %>
  <% if @book.errors.any? %>
    <div class="alert alert-danger">
      <% @book.errors.full_messages.each do |message| %>
        <div><%= message%></div>
      <%end%>
    </div>
  <%end%>
  <div class="mb-3">
    <%= form.label :title, class:"mb-2"%>
    <%= form.text_field :title, class:"form-control", placeholder: "abc@gmail.com"%>
  </div>
  <div class="mb-3">
    <%= form.label :author, class:"mb-2"%>
    <%= form.text_field :author, class:"form-control", placeholder:"Author name"%>
  </div>

  <div class="mb-3">
    <%= form.label :volume, class:"mb-2"%>
    <%= form.text_field :volume, class:"form-control", placeholder:"Volume"%>
  </div>

  <div class="mb-3">
    <%= form.label :published_in, class:"mb-2"%>
    <%= form.text_field :published_in, class:"form-control", placeholder:"published date"%>
  </div>

  <div class="mb-3">
    <%= form.submit "Add Book", class:"btn btn-primary"%>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <div class="container">
      <%= render partial: "shared/flash"%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice]%>
  </div>
<% end%>

<% if flash[:alert] %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert]%>
  </div>
<% end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%=link_to "LibHome", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", root_path, class: "nav-link active"%>
      </div>

      <div class="navbar-nav ms-auto mb-2">
          <% if Current.user%>
              <span class="text-primary d-flex align-items-center border rounded fw-bold me-2">
                <%= link_to "See Books", see_books_path, class:"nav-link"%>
              </span>
              <span class="text-primary d-flex align-items-center border rounded fw-bold ps-2 pe-2">
                <%= Current.user.email%>
              </span>
              <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-outline-secondary ms-2"%>
          <% else %>
            <%= link_to "Sign Up", sign_up_url, class: "nav-link" %>
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          <%end%>
      </div>
    </div>
  </div>
</nav>